name: New Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init values
        id: values
        run: |
          version=$(grep -Po -m 1 '(?<=versionName ).*' ./app/build.gradle | tr -d \")
          echo "name=hKtweaks v$version" >> $GITHUB_OUTPUT
          echo "tag=v$(echo $version | tr -d "\- OneUI")" >> $GITHUB_OUTPUT
          echo "apk=hKtweaks_v$(echo $version | sed -r 's/[- ]+/_/g')" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git tag ${{ steps.values.outputs.tag }} || true
          git push origin ${{ steps.values.outputs.tag }} || true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.values.outputs.tag }}
          name: ${{ steps.values.outputs.name }}
          body: changelog
          files: ./app/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
